# -*- coding: utf-8 -*-
import pathlib
import shutil
import keras_autodoc

PAGES = {        
    'documentation/queries.md': [
        'querier.concat',        
        'querier.delete',        
        'querier.drop',        
        'querier.filtr',        
        'querier.join',        
        'querier.request',        
        'querier.select',        
        'querier.setwhere',        
        'querier.summarize',        
        'querier.update'        
    ],
    'documentation/querier.md': [
        'querier.Querier',        
    ],
}

querier_dir = pathlib.Path(__file__).resolve().parents[1]


def generate(dest_dir):
    template_dir = querier_dir / 'docs' / 'templates'

    doc_generator = keras_autodoc.DocumentationGenerator(
        PAGES,
        'https://github.com/Techtonique/querier/blob/master',
        template_dir,
        #querier_dir / 'examples'
    )
    doc_generator.generate(dest_dir)

    readme = (querier_dir / 'README.md').read_text()
    index = (template_dir / 'index.md').read_text()
    index = index.replace('{{autogenerated}}', readme[readme.find('##'):])
    (dest_dir / 'index.md').write_text(index, encoding='utf-8')
    shutil.copyfile(querier_dir / 'CONTRIBUTING.md',
                    dest_dir / 'contributing.md')
    #shutil.copyfile(querier_dir / 'docs' / 'extra.css',
    #                dest_dir / 'extra.css')


if __name__ == '__main__':
    generate(querier_dir / 'docs' / 'sources')